<?php
	$LAN['LANGNAME'] = "Français";
	$LAN['FLAG'] = "fr";
	
	$LAN['TITLE'] = "GSNet - Game Server Live Status, Banners, Usability monitoring";
	$LAN['KEYWORDS'] = "server ip port game monitor list tracker signature samp san andreas multiplayer counter strike source csgo mta fivem just cause mafia2 unturned";
	$LAN['DESCRIPTION'] = "Game Server Monitoring, List, Banner, Signature, Usability monitoring. GSNet";
	$LAN['HOME'] = "Accueil";
	$LAN['ADD_SERVER'] = "Ajouter Serveur";
	$LAN['FORUMS'] = "Forum";
	$LAN['DONATE'] = "Faire un don";
	$LAN['STATUS'] = "Status";
	
	$LAN['SEARCH'] = "Rechercher";
	$LAN['NAME'] = "Nom";
	$LAN['SRVNAME'] = "Nom du Serveur";
	$LAN['ALL_GAMES'] = "Tout les Jeux";
	$LAN['LOCATION'] = "Localisation";
	$LAN['ALL_LOCATIONS'] = "Toutes Localisations";
	$LAN['ADDITION_SETTINGS'] = "Paramètres Additionnels";
	$LAN['NOT_FULL'] = "Pas Plein";
	$LAN['NO_PASSWORD'] = "Pas de Mot de Passe";
	$LAN['NOT_EMPTY'] = "Pas Vide";
	$LAN['GAME'] = "Jeux";
	$LAN['PLAYERS'] = "Joueurs";
	$LAN['MAP'] = "Map";
	$LAN['IPPORT'] = "IP:Port";
	$LAN['IP'] = "IP";
	$LAN['PORT'] = "Port";
	$LAN['ADD_SERVER'] = "Ajouter Serveur";
	$LAN['SUBMIT'] = "Envoyer";
	$LAN['ERROR_MSG'] = "Oups! Quelque chose c'est mal passé";
	$LAN['ERROR_MSG_GAME'] = "Mauvais Type de Jeu.";
	$LAN['ERROR_INVAILD_IP'] = "Adresse IP invalide.";
	$LAN['ERROR_INVAILD_PORT'] = "Port Invalide.";
	$LAN['SUCCESS_MSG'] = "Succès!";
	$LAN['ERROR_ALREAD_EXIST'] = "Ce Serveur existe déjà!";
	$LAN['ADD_SERVER_SUCCESS_MSG'] = "Vous avez ajoutez ce serveur sur GSNet! Ce serveur sera surveillé, vous pouvez obtenir le status du serveur moins de 5 minutes après qu'il soit en ligne.";
	$LAN['SERVER_INFORMATION'] = "Informations Serveurs";
	$LAN['ERROR_SERVER_NOT_FOUND'] = "Ce serveur est introuvable dans notre base de données.";
	$LAN['LAST_UPDATE'] = "Dernière Mise à Jour(UTC)";
	$LAN['SERVICES'] = "Services";
	$LAN['HCOUNT'] = "HCount";
	$LAN['HSIGN'] = "Signature";
	$LAN['HSIGN_HELP'] = "Changer la couleur,tcolor pour changer la couleur de la police, changer lan pour changer la langue";
	$LAN['HCOUNT_HELP'] = "Pour changer la couleur de l'image, changez &color=255,255,255 par la couleur RGB de votre choix";
	$LAN['SERVER_OFFLINE'] = "Le serveur est hors-ligne !";
	$LAN['ADD_SERVER_LOGIN_REQUIRED'] = "To add a server, you must login to our forums first. <a class='alert-link' href='http://www.gsnet.work/forums/ucp.php?mode=login' target='_blank'>Login Now</a>";
	$LAN['ADD_SERVER_CONNECT_FAILED'] = "We have tried to connect to this server for 3 times, but it seems that the server does not give response, please check your server online. If you need help, please go to our forum.";
	$LAN['ADD_SERVER_TIPS'] = "If your server always could not be queried, it may caused by our server that could not connect to your game server, consider <a class='alert-link' href='http://http://www.gsnet.work/forums/viewforum.php?f=5' target='_blank'>post it on our forum for support</a>.";
	$LAN['IN'] = "in";
	$LAN['SERVERS'] = "serveurs";
?>