<?php
	$LAN['LANGNAME'] = "Nederlands";
	$LAN['FLAG'] = "nl";
	
	$LAN['TITLE'] = "Game Server Netwerk | GSNET - Check hier de live status, banners en ip's van uw favoriete server of voeg je eigen toe!";
	$LAN['KEYWORDS'] = "server ip port game monitor list tracker signature samp san andreas multiplayer counter strike source csgo mta fivem just cause mafia2 unturned";
	$LAN['DESCRIPTION'] = "uw gaming server status bijhouden, de lijst bekijken, de banners bekijken, en nog veel meer. Game Server Netwerk | GSNET";
	
	$LAN['HOME'] = "Hoofdpagina";
	$LAN['ADD_SERVER'] = "Voeg uw server toe";
	$LAN['FORUMS'] = "De forums";
	$LAN['DONATE'] = "Donaties";
	$LAN['STATUS'] = "De status";
	
	$LAN['SEARCH'] = "Zoek";
	$LAN['NAME'] = "Naam";
	$LAN['SRVNAME'] = "Server Naam";
	$LAN['ALL_GAMES'] = "Alle spellen";
	$LAN['LOCATION'] = "Locatie";
	$LAN['ALL_LOCATIONS'] = "Alle locaties";
	$LAN['ADDITION_SETTINGS'] = "Extra instellingen";
	$LAN['NOT_FULL'] = "Zit niet vol";
	$LAN['NO_PASSWORD'] = "Geen wachtwoord";
	$LAN['NOT_EMPTY'] = "Niet leeg";
	$LAN['GAME'] = "Spel";
	$LAN['PLAYERS'] = "Spelers";
	$LAN['MAP'] = "De map";
	$LAN['IPPORT'] = "IP:Port";
	$LAN['IP'] = "IP";
	$LAN['PORT'] = "Port";
	$LAN['QUERYPORT'] = "Wachtrij Port";
	$LAN['ADD_SERVER'] = "Voeg uw server toe";
	$LAN['SUBMIT'] = "Verzend";
	$LAN['ERROR_MSG'] = "Oeps! Er is iets misgegaan.";
	$LAN['ERROR_MSG_GAME'] = "Verkeerde gametype.";
	$LAN['ERROR_INVAILD_IP'] = "Verkeerd ip ingevoerd.";
	$LAN['ERROR_INVAILD_PORT'] = "verkeerde port ingevoerd.";
	$LAN['SUCCESS_MSG'] = "Gelukt!";
	$LAN['ERROR_ALREAD_EXIST'] = "Deze server bestaat al!";
	$LAN['ADD_SERVER_SUCCESS_MSG'] = "Je hebt jou server Geregristreed op GSNET! We zullen de server in de gaten houden, Hij wordt nu gescand om de status bij te houden.";
	$LAN['SERVER_INFORMATION'] = "Server informatie";
	$LAN['ERROR_SERVER_NOT_FOUND'] = "De server is niet gevonden";
	$LAN['LAST_UPDATE'] = "laatste update(UTC)";
	$LAN['SERVICES'] = "Diensten";
	$LAN['HCOUNT'] = "HCount";
	$LAN['HSIGN'] = "HSign Banner";
	$LAN['HCOUNT_HELP'] = "Om de kleur te veranderen veranderd u 255,255,255 naar wat je wilt in RGB taal";
	$LAN['HSIGN_HELP'] = "verander de twee 255,255,255 kleur codes om de titel/beschrijvings kleur te veranderen, verander en_us om een andere taal te kiezen";
	$LAN['SERVER_OFFLINE'] = "deze server is offline!";
	$LAN['ADD_SERVER_LOGIN_REQUIRED'] = "Om een server toe te voegen moet je eerst op het forum inloggen... <a class='alert-link' href='http://www.gsnet.work/forums/ucp.php?mode=login' target='_blank'>log nu in!</a>";
	$LAN['ADD_SERVER_CONNECT_FAILED'] = "We hebben 3 keer geprobeerd om te verbinden met de server, check dan of hij online is, als niets helpt ga dan naar het forum";
	$LAN['ADD_SERVER_TIPS'] = "Als je een server met een hostnaam(domein) wilt toevoegen, plaats het dan alstublieft op het <a class='alert-link' href='http://www.gsnet.work/forums/viewtopic.php?f=5&p=5053' target='_blank'>forum</a>.";
	$LAN['IN'] = "in";
	$LAN['SERVERS'] = "servers";
	$LAN['TRACKINGSERVER'] = "Tracking Server";
	$LAN['SERVERINFO'] = "Server Info";
	$LAN['SERVERVAR'] = "Server Variables";
	$LAN['NAME'] = "Name";
	$LAN['SCORE'] = "Score";
	$LAN['PING'] = "Ping";
?>
