<?php
	$LAN['LANGNAME'] = "Turkish";
	$LAN['FLAG'] = "tr";
	
	$LAN['TITLE'] = "GS-M.ORG - Oyun Sunucusu Canlı Sunucu Durumu, Afisler, Kullanılabilirlik izleme";
	$LAN['KEYWORDS'] = "server ip port game monitor list tracker signature samp san andreas multiplayer counter strike source csgo mta fivem just cause mafia2 unturned";
	$LAN['DESCRIPTION'] = "Game Server Monitoring, List, Banner, Signature, Usability monitoring. GS-M.ORG";
	$LAN['HOME'] = "Ana Sayfa";
	$LAN['ADD_SERVER'] = "Sunucu Ekle";
	$LAN['FORUMS'] = "Forum";
	$LAN['DONATE'] = "Donate";
	
	$LAN['SEARCH'] = "Arama";
	$LAN['NAME'] = "İsim";
	$LAN['SRVNAME'] = "Server Adı";
	$LAN['ALL_GAMES'] = "Tum Oyunlar";
	$LAN['LOCATION'] = "Konum";
	$LAN['ALL_LOCATIONS'] = "Tum Konumlar";
	$LAN['ADDITION_SETTINGS'] = "Toplama Ayarları";
	$LAN['NOT_FULL'] = "Dolu Degil";
	$LAN['NO_PASSWORD'] = "Sifre Yok";
	$LAN['NOT_EMPTY'] = "Bos degil";
	$LAN['GAME'] = "Oyun";
	$LAN['PLAYERS'] = "Oyuncular";
	$LAN['MAP'] = "Harita";
	$LAN['IPPORT'] = "IP:Port";
	$LAN['IP'] = "IP";
	$LAN['PORT'] = "Port";
	$LAN['ADD_SERVER'] = "Sunucu Ekle";
	$LAN['SUBMIT'] = "Gonder";
	$LAN['ERROR_MSG'] = "Hata! Bir seyler yanlıs gitti.";
	$LAN['ERROR_MSG_GAME'] = "Yanlıs Oyun Türü.";
	$LAN['ERROR_INVAILD_IP'] = "Gecersiz IP Adresi.";
	$LAN['ERROR_INVAILD_PORT'] = "Gecersiz Port";
	$LAN['SUCCESS_MSG'] = "Basarılı!";
	$LAN['ERROR_ALREAD_EXIST'] = "Bu sunucu zaten var!";
	$LAN['ADD_SERVER_SUCCESS_MSG'] = "Bu sunucuyu GS-M'ye basarıyla eklediniz! Bu sunucu izlenecek, sunucu cevrimici durumdayken sunucu durumunu 5 dakikadan daha kısa sürede alabilirsiniz.";
	$LAN['SERVER_INFORMATION'] = "Sunucu Bilgileri";
	$LAN['ERROR_SERVER_NOT_FOUND'] = "Bu sunucu veritabanımızda mevcut degil.";
	$LAN['LAST_UPDATE'] = "Son Guncelleme (UTC)";
	$LAN['SERVICES'] = "Hizmetler";
	$LAN['HCOUNT'] = "HCount";
	$LAN['HSIGN'] = "Signature";
	$LAN['HSIGN_HELP'] = "Change color,tcolor to change font color, change lan to set language";
	$LAN['HCOUNT_HELP'] = "Resmin rengini değiştirmek için &color=255,255,255 RGB'de ne gibi";
	$LAN['SERVER_OFFLINE'] = "Sunucu cevrimdısı!";
	$LAN['ADD_SERVER_LOGIN_REQUIRED'] = "To add a server, you must login to our forums first. <a class='alert-link' href='http://www.gs-m.org/forums/ucp.php?mode=login' target='_blank'>Login Now</a>";
	$LAN['ADD_SERVER_TIPS'] = "Sunucunuz her zaman sorgulanamadıysa, oyun sunucumuza baglanamayan sunucumuzdan kaynaklanıyor olabilir. <a class='alert-link' href='http://http://www.gs-m.org/forums/viewforum.php?f=5' target='_blank'>Destek için forumumuza gonderin.</a>.";
	$LAN['IN'] = "in";
	$LAN['SERVERS'] = "Sunucu";
?>