<?php
	$LAN['LANGNAME'] = "简体中文";
	$LAN['FLAG'] = "cn";
	
	$LAN['TITLE'] = "Game Server Network | GSNET - 游戏服务器实时状态, 横幅, 可用性检测";
	$LAN['KEYWORDS'] = "server ip port game monitor list tracker signature samp san andreas multiplayer counter strike source csgo mta fivem just cause mafia2 unturned";
	$LAN['DESCRIPTION'] = "游戏服务器状态监控, 列表, 横幅, 签名图片, 可用性检测. Game Server Network | GSNET";
	$LAN['HOME'] = "主页";
	$LAN['ADD_SERVER'] = "添加服务器";
	$LAN['FORUMS'] = "论坛";
	$LAN['DONATE'] = "捐助";
	$LAN['ADS'] = "广告";
	$LAN['SEARCH'] = "搜索";
	$LAN['NAME'] = "名称";
	$LAN['STATUS'] = "状态";
	$LAN['SRVNAME'] = "服务器名称";
	$LAN['ALL_GAMES'] = "所有游戏";
	$LAN['LOCATION'] = "地点";
	$LAN['ALL_LOCATIONS'] = "所有地点";
	$LAN['ADDITION_SETTINGS'] = "附加设置";
	$LAN['NOT_FULL'] = "没有满人";
	$LAN['NO_PASSWORD'] = "没有密码";
	$LAN['NOT_EMPTY'] = "不是没人";
	$LAN['GAME'] = "游戏";
	$LAN['PLAYERS'] = "玩家";
	$LAN['MAP'] = "地图";
	$LAN['IPPORT'] = "IP:端口";
	$LAN['IP'] = "IP";
	$LAN['PORT'] = "端口";
	$LAN['QUERYPORT'] = "查询端口";
	$LAN['ADD_SERVER'] = "添加服务器";
	$LAN['SUBMIT'] = "提交";
	$LAN['ERROR_MSG'] = "发生错误";
	$LAN['ERROR_MSG_GAME'] = "提交的游戏类型错误.";
	$LAN['ERROR_INVAILD_IP'] = "提交的IP地址错误.";
	$LAN['ERROR_INVAILD_PORT'] = "提交的端口号错误.";
	$LAN['SUCCESS_MSG'] = "成功!";
	$LAN['ERROR_ALREAD_EXIST'] = "此服务器已经存在!";
	$LAN['ADD_SERVER_SUCCESS_MSG'] = "成功添加此服务器到GSNET! 服务器现在开始将被监控, 如果此服务器在线, 你将在5分钟内获得服务器状态信息.";
	$LAN['SERVER_INFORMATION'] = "服务器信息";
	$LAN['ERROR_SERVER_NOT_FOUND'] = "此服务器不存在";
	$LAN['LAST_UPDATE'] = "更新时间(UTC)";
	$LAN['SERVICES'] = "服务";
	$LAN['HCOUNT'] = "HCount";
	$LAN['HSIGN'] = "HSign签名";
	$LAN['HCOUNT_HELP'] = "如果要修改图片颜色，修改255,255,255到你想要的颜色(RGB模式)";
	$LAN['HSIGN_HELP'] = "修改255,255,255设置标题/内容文字颜色(RGB模式),修改en_us设置语言";
	$LAN['SERVER_OFFLINE'] = "服务器不在线！";
	$LAN['ADD_SERVER_LOGIN_REQUIRED'] = "你需要先登录我们的论坛以添加服务器。<a class='alert-link' href='http://www.gsnet.work/forums/ucp.php?mode=login' target='_blank'>立刻登录</a>";
	$LAN['ADD_SERVER_CONNECT_FAILED'] = "我们已经尝试连接该服务器3次，但是服务器好像没有响应，请检查服务器是否在线。如果你需要帮助，请<a class='alert-link' href='http://http://www.gsnet.work/forums/viewforum.php?f=5' target='_blank'>前往我们的论坛</a>。";
	$LAN['ADD_SERVER_TIPS'] = "如果你需要添加主机名（域名）形式的服务器，请<a class='alert-link' href='http://www.gsnet.work/forums/viewforum.php?f=5' target='_blank'>前往我们的论坛</a>。";
	$LAN['IN'] = "在";
	$LAN['SERVERS'] = "服务器";
?>